name: Parent Pipeline

on:
  pull_request:
    branches: ["master"]

jobs:
  frontend:
    name: Client Pipeline
    uses: ./.github/workflows/client.yml

  backend:
    name: Backend Pipeline
    uses: ./.github/workflows/backend.yml
